### ISSUE TITLE
Mapping WebSockets to thread names doesn't work properly

### ISSUE THREAD

**Issue by slry** [InnoSWP/InnoSCS#54]
When I pick different question in the bot, sometimes, WebSocket doesn't change.
----thread 1----
![Image](https://user-images.githubusercontent.com/88106430/174682059-1804450b-ab24-40f9-9278-adf94306ede5.png)

![Image](https://user-images.githubusercontent.com/88106430/174682145-7458ea16-63d1-4317-8cd2-5ff867d4b290.png)

---thread 2----

![Image](https://user-images.githubusercontent.com/88106430/174682195-c8a95244-0bbd-4a67-9011-29975646d47f.png)

![Image](https://user-images.githubusercontent.com/88106430/174682241-4562f890-6834-4ba5-8b89-99e1a9483cd6.png)

In the example above second thread just disapeared in the bot chat and next message went to the first thread.

UPD: When thread is assigned to volunteer it disapears from the question list, but still, websockets were changed. My guess is that websockets are assigned to numbers, but not the thread name, therefore when new thread added, it gets the websocket of the previous thread and so on.

![Image](https://user-images.githubusercontent.com/88106430/174682525-3561305b-65ab-43d3-b6fc-49ce249a715d.png)

**Comment by macoyshev** [comment]
Thank @slry for reporting! Actually the problem is that every time when you pick up, give_up or resolve a question, the sequence is changed(mapping stays correct), so you need to check questions every time after these operations. The problem is related with current backend implementation without DB. It's quite inconvenient, I will fix it soon!

![Image](https://user-images.githubusercontent.com/64314280/174790799-f2516e35-451a-4759-92de-6fc1d4b0433a.png)
